packages:
  - 'CalculateNightDays'
  - 'GitlabMrNotice'
  - 'ScheduleJobAgenda'
  - 'TypeScriptStudy'
  - 'Ssr-study'
  - 'DirectDownload'
  - 'Ast'
  - 'llama-index'
  - 'WebSocketStudy'
  - 'retro-app'

